[package]
name = "twister-press"
version = "0.1.0"
authors = ["Nate Strandberg <nater540@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m-rtic = "0.5.6"
panic-semihosting = "0.5.6"
nrf52832-hal = "0.12.2"
